### ISSUE TITLE
Add i18n to support en

### ISSUE THREAD

**Issue by wei** [super-inspire/super-inspire-frontend#5]
Options: 
* [i18next](https://github.com/i18next/react-i18next) [[demo]](https://codesandbox.io/s/8n252n822)
* [ttag](https://hackernoon.com/simple-i18n-for-create-react-app-with-ttag-4c2892343201) [[demo]](https://ttag-org.github.io/CRA-runtime-example/)

**Comment by hileix** [comment]
嗯，这个接下来可以支持一下。
